-- VINCO native user management -- one-time, OPTIONAL manual step.
--
-- Run once, manually, in the Supabase Dashboard -> SQL Editor for the
-- VINCO project. Not required for the "Users & Access" feature to work
-- at all: employee/admin/super_admin all map onto Supabase roles that
-- already exist (employee, general_manager, super_admin -- see
-- backend/app/services/user_service.py's ROLE_TO_SUPABASE_ROLE). This
-- script is only needed to make VINCO's "Super User" role (full business
-- access, but not system/user administration) a real, independently
-- enforced role distinct from "Super Admin" (which additionally has
-- admin.users/admin.roles/admin.settings). Until this is run, creating
-- or editing a user with role "super_user" fails with a clear 422 error
-- naming exactly this script.
--
-- Additive only: adds one new enum value and its permission grants.
-- Does not alter, drop, or rename anything that exists today. Safe to
-- run against the live production database -- confirmed by design, not
-- by testing against production (no access to it from here): every
-- statement below is either an enum addition (never fails if the value
-- already exists, given the IF NOT EXISTS guard) or an additive INSERT
-- guarded by ON CONFLICT DO NOTHING.

-- IMPORTANT -- run as two SEPARATE statements/executions (click "Run"
-- once for Step 1, wait for it to finish, then click "Run" again for
-- Step 2). PostgreSQL does not allow a new enum value to be used in the
-- same transaction that adds it -- pasting both steps and running them
-- together in one go can fail with "unsafe use of new value of enum
-- type". Running them as two separate statements avoids that entirely.

-- ---- Step 1 ----
-- Add the new role value to the existing app_role enum.
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'super_user';

-- ---- Step 2 (run after Step 1 has completed) ----
-- Grant it every existing permission except the admin.* ones --
-- "full application access", not "system-level control" (that
-- distinction is the whole point of keeping super_admin separate; see
-- the app's README for the intended role hierarchy). Re-run safe:
-- ON CONFLICT DO NOTHING means running this twice is a no-op the second
-- time, not a duplicate-row error.
-- INSERT INTO public.role_permissions (role, permission)
-- SELECT 'super_user', p
-- FROM unnest(enum_range(NULL::public.app_permission)) AS p
-- WHERE p::text NOT LIKE 'admin.%'
-- ON CONFLICT DO NOTHING;
