"""add supplier vendor intelligence foundation

Revision ID: 02a08df89e1b
Revises: a994d17f4ddb
Create Date: 2026-08-27 02:02:50.701563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a08df89e1b'
down_revision: Union[str, Sequence[str], None] = 'a994d17f4ddb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Purely additive: every new column is nullable, or NOT NULL with a
    server default (matching this project's own established convention,
    e.g. `125d4e231e60`'s `is_tax_recoverable`/`payment_status`), so this
    never fails against a table that already has rows. Nothing existing
    is altered — the autogenerated no-op `document_kind`/`extraction_status`
    type-reassertions (a known SQLite/`native_enum=False` reflection
    artifact, unrelated to this change) were removed from the
    autogenerated draft rather than included.
    """
    with op.batch_alter_table('imported_purchase_order_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vendor_tax_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column(
            'vendor_match_status',
            sa.Enum('MATCHED', 'UNMATCHED', 'AMBIGUOUS', name='purchaseordermatchstatus', native_enum=False),
            server_default='UNMATCHED',
            nullable=False,
        ))
        batch_op.add_column(sa.Column('matched_vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('candidate_vendor_ids', sa.Text(), nullable=True))
        batch_op.create_foreign_key(
            'fk_imported_purchase_order_candidates_matched_vendor', 'vendors', ['matched_vendor_id'], ['id'],
        )

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_purchase_orders_vendor', 'vendors', ['vendor_id'], ['id'],
        )

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column(
            'default_currency',
            sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False),
            server_default='AED',
            nullable=False,
        ))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.create_index(batch_op.f('ix_vendors_tax_number'), ['tax_number'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_tax_number'))
        batch_op.drop_column('is_active')
        batch_op.drop_column('default_currency')
        batch_op.drop_column('tax_number')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_orders_vendor', type_='foreignkey')
        batch_op.drop_column('vendor_id')

    with op.batch_alter_table('imported_purchase_order_candidates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_purchase_order_candidates_matched_vendor', type_='foreignkey')
        batch_op.drop_column('candidate_vendor_ids')
        batch_op.drop_column('matched_vendor_id')
        batch_op.drop_column('vendor_match_status')
        batch_op.drop_column('vendor_tax_number')
        batch_op.drop_column('vendor_name')
