"""phase 2: cost tax retention and payment status tracking

Revision ID: 125d4e231e60
Revises: 62229cfed8a9
Create Date: 2026-08-23 20:20:00.617672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125d4e231e60'
down_revision: Union[str, Sequence[str], None] = '62229cfed8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actual_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_tax_recoverable', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', name='costpaymentstatus', native_enum=False), server_default='UNPAID', nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_check_constraint('ck_actual_costs_tax_amount_range', 'tax_amount IS NULL OR (amount >= 0 AND tax_amount >= 0 AND tax_amount <= amount) OR (amount < 0 AND tax_amount <= 0 AND tax_amount >= amount)')

    with op.batch_alter_table('estimated_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_retention_release', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('is_retention_release')

    with op.batch_alter_table('estimated_costs', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('unit_rate')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')

    with op.batch_alter_table('actual_costs', schema=None) as batch_op:
        batch_op.drop_constraint('ck_actual_costs_tax_amount_range', type_='check')
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('is_tax_recoverable')
        batch_op.drop_column('tax_amount')
        batch_op.drop_column('reference_number')

    # ### end Alembic commands ###
