"""add ocr extraction engine column

Revision ID: 1cbbf15aef72
Revises: df308de183b5
Create Date: 2026-08-24 09:05:39.318289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbbf15aef72'
down_revision: Union[str, Sequence[str], None] = 'df308de183b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imported_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extraction_engine', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imported_documents', schema=None) as batch_op:
        batch_op.drop_column('extraction_engine')

    # ### end Alembic commands ###
