"""add invoice tax and retention tracking

Revision ID: 62229cfed8a9
Revises: 638f059253b1
Create Date: 2026-08-23 19:59:30.042686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62229cfed8a9'
down_revision: Union[str, Sequence[str], None] = '638f059253b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.create_check_constraint('ck_invoices_retention_amount_range', 'retention_amount IS NULL OR (amount >= 0 AND retention_amount >= 0 AND retention_amount <= amount) OR (amount < 0 AND retention_amount <= 0 AND retention_amount >= amount)')
        batch_op.create_check_constraint('ck_invoices_tax_amount_range', 'tax_amount IS NULL OR (amount >= 0 AND tax_amount >= 0 AND tax_amount <= amount) OR (amount < 0 AND tax_amount <= 0 AND tax_amount >= amount)')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('ck_invoices_tax_amount_range', type_='check')
        batch_op.drop_constraint('ck_invoices_retention_amount_range', type_='check')
        batch_op.drop_column('retention_amount')
        batch_op.drop_column('tax_amount')

    # ### end Alembic commands ###
