"""postgresql baseline schema

Revision ID: 926e160784a0
Revises: cb86207a716e
Create Date: 2026-08-29 10:02:27.686836

The 14 migrations before this one contain SQLite-only DDL (raw integer
boolean defaults, batch-mode ALTER TABLE) baked into their historical
`upgrade()`/`downgrade()` bodies, and replaying them against PostgreSQL
fails partway through (empirically confirmed against a real, disposable
Postgres instance -- see 125d4e231e60, which errors on a boolean/integer
default type mismatch). Rather than editing every historical file, this
single migration creates the *entire current schema* from scratch, and
only does anything on PostgreSQL: on SQLite it is a no-op, because a
SQLite database has already reached this exact schema by walking the 14
migrations before it. A fresh PostgreSQL database instead runs
`alembic stamp cb86207a716e` (marking the SQLite-only history as already
applied without executing any of it) followed by `alembic upgrade head`,
which then only executes this migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926e160784a0'
down_revision: Union[str, Sequence[str], None] = 'cb86207a716e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name != "postgresql":
        # SQLite reaches this exact schema by walking the 14 migrations
        # before this one -- see the module docstring.
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('trade_license_number', sa.String(length=100), nullable=True),
    sa.Column('default_currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['cost_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', name='employmentstatus', native_enum=False), server_default='ACTIVE', nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deductions', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', name='payrollstatus', native_enum=False), server_default='DRAFT', nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('period_end >= period_start', name='ck_payroll_records_period_range'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_trade_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'TENDERING', 'SUBMITTED', 'AWARDED', 'LOST', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CLOSED', 'CANCELLED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('tender_submission_date', sa.Date(), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_completion_date', sa.Date(), nullable=True),
    sa.Column('actual_completion_date', sa.Date(), nullable=True),
    sa.Column('defects_liability_end_date', sa.Date(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('contract_currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('winning_quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['primary_trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['winning_quotation_version_id'], ['quotation_versions.id'], name='fk_projects_winning_quotation_version', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code', name='uq_projects_project_code')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_type', sa.Enum('SUPPLIER', 'SUBCONTRACTOR', name='vendortype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('default_currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_index(op.f('ix_vendors_tax_number'), 'vendors', ['tax_number'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('CLIENT', 'VENDOR', name='invoicedirection', native_enum=False), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'DISPUTED', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('retention_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(direction = 'CLIENT' AND client_id IS NOT NULL AND vendor_id IS NULL) OR (direction = 'VENDOR' AND vendor_id IS NOT NULL AND client_id IS NULL)", name='ck_invoices_direction_party'),
    sa.CheckConstraint('retention_amount IS NULL OR (amount >= 0 AND retention_amount >= 0 AND retention_amount <= amount) OR (amount < 0 AND retention_amount <= 0 AND retention_amount >= amount)', name='ck_invoices_retention_amount_range'),
    sa.CheckConstraint('tax_amount IS NULL OR (amount >= 0 AND tax_amount >= 0 AND tax_amount <= amount) OR (amount < 0 AND tax_amount <= 0 AND tax_amount >= amount)', name='ck_invoices_tax_amount_range'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('REFERRAL', 'TENDER', 'WEBSITE', 'EXISTING_CLIENT', 'OTHER', name='leadsource', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST', 'ON_HOLD', name='leadstatus', native_enum=False), server_default='NEW', nullable=False),
    sa.Column('estimated_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('converted_project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('probability IS NULL OR (probability >= 0 AND probability <= 100)', name='ck_leads_probability_range'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['converted_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LEAD', 'TENDERING', 'SUBMITTED', 'AWARDED', 'LOST', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CLOSED', 'CANCELLED', name='projectstatus', native_enum=False), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_variations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('variation_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('proposed_value_change', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('approved_value_change', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estimated_cost_change', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED', name='variationstatus', native_enum=False), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('decided_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('items_description', sa.Text(), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED', name='purchaserequeststatus', native_enum=False), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number', name='uq_quotations_reference_number')
    )
    op.create_table('actual_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('cost_category_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_tax_recoverable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PARTIALLY_PAID', 'PAID', name='costpaymentstatus', native_enum=False), server_default='UNPAID', nullable=False),
    sa.Column('incurred_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('tax_amount IS NULL OR (amount >= 0 AND tax_amount >= 0 AND tax_amount <= amount) OR (amount < 0 AND tax_amount <= 0 AND tax_amount >= amount)', name='ck_actual_costs_tax_amount_range'),
    sa.ForeignKeyConstraint(['cost_category_id'], ['cost_categories.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_award_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('awarded_quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('po_reference_number', sa.String(length=100), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_quotation_version_id'], ['quotation_versions.id'], name='fk_client_award_evidence_awarded_quotation_version', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_reference_number', name='uq_client_award_evidence_po_reference_number')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('BANK_TRANSFER', 'CHEQUE', 'CASH', 'CARD', 'OTHER', name='paymentmethod', native_enum=False), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('is_retention_release', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('purchase_request_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='purchaseorderstatus', native_enum=False), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number', name='uq_purchase_orders_po_number')
    )
    op.create_table('quotation_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVISED', 'WON', 'LOST', 'WITHDRAWN', 'EXPIRED', name='quotationstatus', native_enum=False), nullable=False),
    sa.Column('quoted_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id', 'version_number', name='uq_quotation_version_number')
    )
    op.create_table('boqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_version_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version_id', sa.Integer(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'TERMINATED', name='contractstatus', native_enum=False), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_contracts_project_id'),
    sa.UniqueConstraint('quotation_version_id', name='uq_contracts_quotation_version_id')
    )
    op.create_table('estimate_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('revision_number > 0', name='ck_estimate_revisions_revision_number_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'revision_number', name='uq_estimate_revision_number')
    )
    op.create_index('uq_estimate_revisions_one_final_per_project', 'estimate_revisions', ['project_id'], unique=True, sqlite_where=sa.text('is_final = 1'), postgresql_where=sa.text('is_final = true'))
    op.create_table('google_drive_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('QUOTATION', 'BOQ', 'CONTRACT', 'INVOICE', 'DRAWING', 'PHOTO', 'CORRESPONDENCE', 'OTHER', name='documenttype', native_enum=False), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('web_link', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id')
    )
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'CANCELLED', name='receiptstatus', native_enum=False), nullable=False),
    sa.Column('received_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boq_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boq_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimated_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('estimate_revision_id', sa.Integer(), nullable=True),
    sa.Column('cost_category_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cost_category_id'], ['cost_categories.id'], ),
    sa.ForeignKeyConstraint(['estimate_revision_id'], ['estimate_revisions.id'], name='fk_estimated_costs_estimate_revision_id'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quotation_version_id'], ['quotation_versions.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('LOCAL', 'GOOGLE_DRIVE', name='documentsourcetype', native_enum=False), nullable=False),
    sa.Column('document_kind', sa.Enum('QUOTATION', 'BOQ', 'PURCHASE_ORDER', 'UNKNOWN', name='importdocumentkind', native_enum=False), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'EXTRACTING', 'EXTRACTION_COMPLETE', 'FAILED', 'UNSUPPORTED', 'OCR_REQUIRED', 'MULTIPLE_QUOTATIONS_DETECTED', 'SEGMENTS_PROPOSED', name='extractionstatus', native_enum=False), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('raw_extracted_data', sa.Text(), nullable=True),
    sa.Column('extraction_engine', sa.String(length=20), nullable=True),
    sa.Column('review_status', sa.Enum('NEEDS_REVIEW', 'CONFIRMED', 'REJECTED', name='importreviewstatus', native_enum=False), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_client_id', sa.Integer(), nullable=True),
    sa.Column('resulting_project_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quotation_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('resulting_boq_id', sa.Integer(), nullable=True),
    sa.Column('resulting_client_award_evidence_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resulting_boq_id'], ['boqs.id'], ),
    sa.ForeignKeyConstraint(['resulting_client_award_evidence_id'], ['client_award_evidence.id'], ),
    sa.ForeignKeyConstraint(['resulting_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['resulting_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resulting_quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['resulting_quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imported_documents_file_hash'), 'imported_documents', ['file_hash'], unique=False)
    op.create_table('receipt_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_line_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_lines.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('IMPORTED', 'EXTRACTED', 'EDITED', 'CONFIRMED', 'REJECTED', 'SEGMENTED', name='importauditeventtype', native_enum=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_client_award_evidence_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('po_reference_number', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'UNMATCHED', 'AMBIGUOUS', name='clientawardevidencematchstatus', native_enum=False), nullable=False),
    sa.Column('matched_quotation_id', sa.Integer(), nullable=True),
    sa.Column('candidate_quotation_ids', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_tax_number', sa.String(length=50), nullable=True),
    sa.Column('vendor_match_status', sa.Enum('MATCHED', 'UNMATCHED', 'AMBIGUOUS', name='clientawardevidencematchstatus', native_enum=False), nullable=False),
    sa.Column('matched_vendor_id', sa.Integer(), nullable=True),
    sa.Column('candidate_vendor_ids', sa.Text(), nullable=True),
    sa.Column('raw_values', sa.Text(), nullable=True),
    sa.Column('field_confidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.ForeignKeyConstraint(['matched_quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['matched_vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imported_document_id')
    )
    op.create_table('imported_document_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('boundary_confidence', sa.String(length=20), nullable=True),
    sa.Column('boundary_signals', sa.Text(), nullable=True),
    sa.Column('detected_quotation_number', sa.String(length=100), nullable=True),
    sa.Column('detected_quotation_date', sa.Date(), nullable=True),
    sa.Column('review_status', sa.Enum('PROPOSED', 'ACCEPTED', 'LOCKED', 'CONFIRMED', 'REJECTED', 'EXCLUDED_NOT_A_QUOTATION', name='segmentreviewstatus', native_enum=False), nullable=False),
    sa.Column('reviewer_adjusted', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_client_id', sa.Integer(), nullable=True),
    sa.Column('resulting_project_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quotation_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('resulting_boq_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.ForeignKeyConstraint(['resulting_boq_id'], ['boqs.id'], ),
    sa.ForeignKeyConstraint(['resulting_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['resulting_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resulting_quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['resulting_quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_boq_line_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('imported_document_segment_id', sa.Integer(), nullable=True),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('group_label', sa.String(length=255), nullable=True),
    sa.Column('item_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_label', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extracted_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('calculated_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_flagged', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.ForeignKeyConstraint(['imported_document_segment_id'], ['imported_document_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_quotation_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('imported_document_segment_id', sa.Integer(), nullable=True),
    sa.Column('quotation_number', sa.String(length=100), nullable=True),
    sa.Column('quotation_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_values', sa.Text(), nullable=True),
    sa.Column('field_confidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.ForeignKeyConstraint(['imported_document_segment_id'], ['imported_document_segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imported_document_segment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name != "postgresql":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imported_quotation_candidates')
    op.drop_table('imported_boq_line_candidates')
    op.drop_table('imported_document_segments')
    op.drop_table('imported_client_award_evidence_candidates')
    op.drop_table('import_audit_log_entries')
    op.drop_table('receipt_lines')
    op.drop_index(op.f('ix_imported_documents_file_hash'), table_name='imported_documents')
    op.drop_table('imported_documents')
    op.drop_table('estimated_costs')
    op.drop_table('boq_line_items')
    op.drop_table('receipts')
    op.drop_table('purchase_order_lines')
    op.drop_table('google_drive_documents')
    op.drop_index('uq_estimate_revisions_one_final_per_project', table_name='estimate_revisions', sqlite_where=sa.text('is_final = 1'), postgresql_where=sa.text('is_final = true'))
    op.drop_table('estimate_revisions')
    op.drop_table('contracts')
    op.drop_table('boqs')
    op.drop_table('quotation_versions')
    op.drop_table('purchase_orders')
    op.drop_table('payments')
    op.drop_table('client_award_evidence')
    op.drop_table('actual_costs')
    op.drop_table('quotations')
    op.drop_table('purchase_requests')
    op.drop_table('project_variations')
    op.drop_table('project_status_history')
    op.drop_table('leads')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_vendors_tax_number'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_table('projects')
    op.drop_table('payroll_records')
    op.drop_table('contacts')
    op.drop_table('trades')
    op.drop_table('employees')
    op.drop_table('cost_categories')
    op.drop_table('companies')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
