"""add purchase order ingestion foundation

Revision ID: a994d17f4ddb
Revises: 0d8c242638a2
Create Date: 2026-08-25 19:33:00.229486

Adds `purchase_orders` (see `app.models.purchase_order.PurchaseOrder`) and
`imported_purchase_order_candidates` (the staging layer for PO ingestion,
see `app.models.import_staging.ImportedPurchaseOrderCandidate`), plus the
`imported_documents.resulting_purchase_order_id` FK a confirmed PO
document points at.

No migration step is needed for the two new enum values used elsewhere in
this change (`ImportDocumentKind.PURCHASE_ORDER`,
`PurchaseOrderMatchStatus`): every enum in this schema is stored
`native_enum=False` (a plain VARCHAR with no CHECK constraint) — same
reasoning already documented in `0d8c242638a2`'s migration for
`ExtractionStatus.SEGMENTS_PROPOSED`. Autogenerate's reported "type
change" on `imported_documents.document_kind`/`extraction_status`
(VARCHAR -> Enum(native_enum=False)) is exactly that same false positive
(a growing declared-length string vs. an unchanged actual column type)
and has been dropped from this migration rather than issuing a no-op
`ALTER COLUMN`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a994d17f4ddb'
down_revision: Union[str, Sequence[str], None] = '0d8c242638a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('awarded_quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('po_reference_number', sa.String(length=100), nullable=False),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_quotation_version_id'], ['quotation_versions.id'], name='fk_purchase_orders_awarded_quotation_version', use_alter=True),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_reference_number', name='uq_purchase_orders_po_reference_number')
    )
    op.create_table('imported_purchase_order_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('po_reference_number', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Enum('MATCHED', 'UNMATCHED', 'AMBIGUOUS', name='purchaseordermatchstatus', native_enum=False), nullable=False),
    sa.Column('matched_quotation_id', sa.Integer(), nullable=True),
    sa.Column('candidate_quotation_ids', sa.Text(), nullable=True),
    sa.Column('raw_values', sa.Text(), nullable=True),
    sa.Column('field_confidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.ForeignKeyConstraint(['matched_quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imported_document_id')
    )
    with op.batch_alter_table('imported_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resulting_purchase_order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_imported_documents_resulting_purchase_order', 'purchase_orders',
            ['resulting_purchase_order_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imported_documents', schema=None) as batch_op:
        batch_op.drop_constraint('fk_imported_documents_resulting_purchase_order', type_='foreignkey')
        batch_op.drop_column('resulting_purchase_order_id')

    op.drop_table('imported_purchase_order_candidates')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
