"""add estimate revisions for estimating accuracy history

Revision ID: f45d5a6cea55
Revises: 125d4e231e60
Create Date: 2026-08-23 20:34:41.933013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45d5a6cea55'
down_revision: Union[str, Sequence[str], None] = '125d4e231e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('currency', sa.Enum('AED', 'USD', 'EUR', 'GBP', 'SAR', name='currency', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('revision_number > 0', name='ck_estimate_revisions_revision_number_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'revision_number', name='uq_estimate_revision_number')
    )
    with op.batch_alter_table('estimate_revisions', schema=None) as batch_op:
        batch_op.create_index('uq_estimate_revisions_one_final_per_project', ['project_id'], unique=True, sqlite_where=sa.text('is_final = 1'))

    with op.batch_alter_table('estimated_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate_revision_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_estimated_costs_estimate_revision_id', 'estimate_revisions', ['estimate_revision_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimated_costs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estimated_costs_estimate_revision_id', type_='foreignkey')
        batch_op.drop_column('estimate_revision_id')

    with op.batch_alter_table('estimate_revisions', schema=None) as batch_op:
        batch_op.drop_index('uq_estimate_revisions_one_final_per_project', sqlite_where=sa.text('is_final = 1'))

    op.drop_table('estimate_revisions')
    # ### end Alembic commands ###
