"""add import staging tables for local document import

Revision ID: df308de183b5
Revises: d4edf16ac948
Create Date: 2026-08-23 21:59:22.567907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df308de183b5'
down_revision: Union[str, Sequence[str], None] = 'd4edf16ac948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('LOCAL', 'GOOGLE_DRIVE', name='documentsourcetype', native_enum=False), nullable=False),
    sa.Column('document_kind', sa.Enum('QUOTATION', 'BOQ', 'UNKNOWN', name='importdocumentkind', native_enum=False), nullable=False),
    sa.Column('original_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('extension', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'EXTRACTING', 'EXTRACTION_COMPLETE', 'FAILED', 'UNSUPPORTED', 'OCR_REQUIRED', name='extractionstatus', native_enum=False), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('raw_extracted_data', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('NEEDS_REVIEW', 'CONFIRMED', 'REJECTED', name='importreviewstatus', native_enum=False), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_client_id', sa.Integer(), nullable=True),
    sa.Column('resulting_project_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quotation_id', sa.Integer(), nullable=True),
    sa.Column('resulting_quotation_version_id', sa.Integer(), nullable=True),
    sa.Column('resulting_boq_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['resulting_boq_id'], ['boqs.id'], ),
    sa.ForeignKeyConstraint(['resulting_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['resulting_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resulting_quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['resulting_quotation_version_id'], ['quotation_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_documents_file_hash'), ['file_hash'], unique=False)

    op.create_table('import_audit_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('IMPORTED', 'EXTRACTED', 'EDITED', 'CONFIRMED', 'REJECTED', name='importauditeventtype', native_enum=False), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_boq_line_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=False),
    sa.Column('group_label', sa.String(length=255), nullable=True),
    sa.Column('item_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_label', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('extracted_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('calculated_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('amount_flagged', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_quotation_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_document_id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=100), nullable=True),
    sa.Column('quotation_date', sa.Date(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('net_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('tax_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw_values', sa.Text(), nullable=True),
    sa.Column('field_confidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['imported_document_id'], ['imported_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imported_document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imported_quotation_candidates')
    op.drop_table('imported_boq_line_candidates')
    op.drop_table('import_audit_log_entries')
    with op.batch_alter_table('imported_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_documents_file_hash'))

    op.drop_table('imported_documents')
    # ### end Alembic commands ###
