// This file is automatically generated. Do not edit it directly.
// EXCEPTION (VINCO desktop): the `auth.storage` and `auth.flowType` lines
// below are deliberate, minimal hand edits -- see src/lib/tauri-storage.ts
// (why the Tauri build needs a different session-storage backend than the
// web build's localStorage) and src/lib/tauri-auth.ts (why the desktop
// OAuth callback needs PKCE's short-lived code instead of tokens directly
// in a vinco:// URL). Nothing else in this file changes; regenerating it
// will need these two lines re-applied.
import { createClient } from '@supabase/supabase-js';
import { isTauri } from '@tauri-apps/api/core';

import { tauriDesktopStorage } from '@/lib/tauri-storage';

import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: isTauri() ? tauriDesktopStorage : typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      // Supabase JS already auto-detects and exchanges a `?code=` on page
      // load the same way it auto-detects `#access_token=` (both covered
      // by the default `detectSessionInUrl: true`), so this is a safe,
      // behavior-preserving switch for the web build. It's required for
      // desktop: the alternative (implicit flow) would put the actual
      // access/refresh tokens directly in the vinco:// callback URL,
      // which OS-level deep-link delivery can expose more than a normal
      // page navigation does (e.g. via process argv on Windows/Linux);
      // PKCE instead exchanges a single-use code for the session, with
      // the verifier never leaving this device.
      flowType: 'pkce',
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

